[phases.install]
aptPkgs = ['wget']
cmds = [
    'wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm',
    "pnpm i --frozen-lockfile",
]

[phases.build]
cms = "pnpm build"

[start]
cmd = "pnpm start"